# This workflows will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries


name: deploy-pypi

on:
  release:
    types: [created]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install muid
        pip install numpy
        pip install pathlib
        pip install contexttimer
        pip install requests
        pip install getjson
        pip install tensorflow
        pip install setuptools wheel twine
    - name: Build and publish
      env:
        MICRO_TEST_CONFIG_URL: ${{secrets.MICRO_TEST_CONFIG_URL}}
        MICRO_TEST_CONFIG_FAILOVER_URL: ${{secrets.MICRO_TEST_CONFIG_FAILOVER_URL}}
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        python setup.py sdist bdist_wheel
        twine upload dist/*
